### ISSUE TITLE
Week 7 ready for review

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/IndieProjectCalebKrause#7]
@pawaitemadisoncollege - week 7 is complete

![image](https://user-images.githubusercontent.com/63691432/109930168-f275bc80-7c8c-11eb-8b40-ed81dd7d9210.png)

# What were your key learning points/takeaways?
- My takeaways were that it's a lot more straightforward than I anticipated. Key learning points being that the context and web xml are the drivers for this entire process. 
# What challenged you?
- I didn't have any issues with this particular exercise. I followed along the videos and everything went the way it was supposed to.
# What problems did you solve and what resources did you use to solve them?
- No problems to solve just tweaked things for my indie project as we were working through them in the videos. I'm glad you did a video on user login since I'm pretty sure everybody has that on their project. Probably saved us all some research time.

**Comment by pawaitemadisoncollege** [comment]
Nice job setting up auth in your project @ctkrause. 

Keep in mind that you will want to restrict access not only to the jsps, but any related resources, such as the servlet, to prevent that savvy user from bypassing the jsps.
