### ISSUE TITLE
Week 8 ready for review

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/IndieProjectCalebKrause#8]
@pawaitemadisoncollege  - week 8 is complete.

# What were your key learning points/takeaways?
- Key learning points were the finer points of API consumption. I messed around with quite a few different APIs before resorting to the pet store one because I knew that one would work correctly.

# What challenged you?
- Headers and getting json info back from default xml api. 
- Finding an api that returned data simply enough so that I could call it and compare it in the assertEquals.

# What problems did you solve and what resources did you use to solve them?
- I tried a couple different APIs that wouldn't work for me because the main class was all in lists and then the getter to retrieve a single value was within a different class and I couldn't figure out how to get that working. I tried using Jsoup, but I'm not sure if it's going to be feasible. The screen scraping is based on identifying similar classes within the HTML DOM and I wasn't having much success on the sites I was trying to get job data from. There are some apis already built to search jobs on specific sites and I may try to implement a few of those instead. I realized that it's going to take many, many hours to get all that working correctly so I just went to the simple pet API so I could get credit for this week and struggle my way through those more complex APIs when I've got more time and I'm not doing midterms for other courses. 

[
![image](https://user-images.githubusercontent.com/63691432/111022979-e3cd8a80-839b-11eb-8d14-8826c80c23ec.png)
]

**Comment by pawaitemadisoncollege** [comment]
This api testing looks good @ctkrause.  If you were using in your project, the next step would be to create a PetStoreDao that does this business: https://github.com/ctkrause/IndieProjectCalebKrause/blob/65d5094a30af3200f2a221bb1e3b581459cfd6d4/src/main/test/java/caleb/indie/persistence/testAPI.java#L15-L20.  And externalize the url in a property file.  

If you'd like help working through a more complex api, let me know and I can poke around a little bit at the one you chose.
