### ISSUE TITLE
Checkpoint 3 is ready for review

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/IndieProjectCalebKrause#9]
@pawaitemadisoncollege - checkpoint 3 is ready for review 

Head to http://3.141.155.98:8080/indieProject/ and the main page will display information from the user table. Login to the auth using "jcoyne" as your user and "supersecret1" as the password. Using the wrong password will display an error page.

**Comment by pawaitemadisoncollege** [comment]
Hey @ctkrause I think I missed my window to test this out.  Any chance you can bounce the ec2 instance? I'm guessing maybe some status checks are failing, as I can't access the deployed app right now. 
![Screen Shot 2021-03-24 at 12 32 53 PM](https://user-images.githubusercontent.com/13874466/112356941-11b8a600-8c9d-11eb-9327-941026f45411.png)

**Comment by ctkrause** [comment]
@pawaitemadisoncollege - I've started and stopped my instance and both status checks are passing now. It looks like it's good to go again.

**Comment by pawaitemadisoncollege** [comment]
Hi @ctkrause - that did it thank you!  You hit cp3, and it seems like you have a good foundation built here to now start building some of that core functionality!

Would you like some help with the api implementation that tripped you up in week 8?
